### ISSUE TITLE
Figure 53 misses in dog release 0.19.1, on page 78

### ISSUE THREAD

**Issue by cjvanzwol** [andrewharmellaw/wardley-maps-book#5]
“Figure 53 — The near, the far and the crazy” https://medium.com/wardleymaps/the-play-and-a-decision-to-act-8eb796b1dff1

**Comment by andrewharmellaw** [comment]
You're right - I just checked and Fig 53 is missing from the 0.19.1 version: https://github.com/andrewharmellaw/wardley-maps-book/releases/download/0.19.1/wardley-maps-book.pdf

Thanks for flagging this @cjvanzwol - if you get round to fixing it before me please just submit a PR.  Otherwise, I'll close this issue when I've fixed it.

**Comment by andrewharmellaw** [comment]
Checking further, figs 54 and 55 seem to be missing too.

**Comment by andrewharmellaw** [comment]
Fixed in (pre)release 0.19.2.
